#+Title: Virtual Labs Workshops

* Online version of Virtual Labs Workshops

** Introduction
   Virtual Labs Team would organize workshops and hands-on practice sessions on
   Virtual Labs for interested Science & Engineering Institutions. Training
   sessions would be conducted for faculty members and students of interested
   institutes upon expression of their interest in Virtual Labs workshop.
   
   On completion of the demonstrations and hands-on sessions, the faculty
   members and the students would be encouraged to submit the feedback form to
   the Virtual Labs team. These forms would be compiled and analyzed for
   further improvements in the Virtual Labs.

** Virtual Labs Workshops Pre-requisites
   1. The Institute should be a Central/State University or Institute/college
      approved by AICTE/UGC.
   2. The institute must have an auditorium with a seating capacity of at least
      100 and a designated/common lab space having 35 PCs or more.
   3. In the event that the Internet operates behind a firewall, the specific
      communication ports 3306, 5900, 5902, and 8700 would need to be opened to
      facilitate Virtual Labs network traffic.
   4. http://www.java.com/en/download/index.jsp must be downloadable through
      the Internet and Gmail should be accessible.
*** System configuration required for running Virtual Labs:
    1. Browser: Firefox, Chrome
    2. Plugins: Flash, Java 1.6 version, and IcedTea
    3. JavaScript should be enabled on the browser
    4. No pop-up blockers
    5. Internet connection (1 Mbps) and a multimedia projector
*** Pre steps to be performed for Virtual Labs Workshop:
    1. [[http://vlabs.ac.in/][vlabs page]] should be accessible from the browser.
    2. [[http://vlabs.ac.in/register][Registration]] page should be successfully submitting the registrations.
    3. Within a lab, lab-level and experiment-level feedback links should be
       working within the institute network.

** Past workshops
   Kindly follow the [[link]] to visit the Virtual Labs Worskhops conducted in the past.
 
** Download the form
   Kindly download the [[form][form]], complete the checklist against each pre requisite, scan the
   form and mail it to us at [[engg@vlabs.ac.in]] 


* Virtual Labs College Cloud Edition version of workshops
** Introduction
** Pre Requisites (checklist just like lalit doc)
** Past Workshops (link to college cloud page)
** Download the doc (college cloud doc make in pdf to be downloadable
   make the pre requisites as square boxes to that person can check the boxes
   and scan it to send to us))

** Introduction
   VLEAD (Virtual Labs Engineering and Architecture Division, IIIT-Hyderabad)
   Team would organize workshops and hands-on practice sessions on Virtual Labs
   College Cloud Edition for interested Science & Engineering
   Institutions. Training sessions would be conducted for faculty members and
   students of interested institutes upon expression of their interest in
   this workshop.
   
   On completion of the demonstrations and hands-on sessions, the faculty
   members and the students would be encouraged to submit the feedback form to
   the Virtual Labs team. These forms would be compiled and analyzed for
   further improvements in the Virtual Labs College Cloud Edition.

** Virtual Labs College Cloud Edition Workshop Pre-requisites
   The Institute should be a Central/State University or Institute/college
   approved by AICTE/UGC. Detailed pre-requisites are listed [[link to collegecloud page][here]].

** Past workshops
   Kindly follow the [[link]] to visit the Virtual Labs College Cloud Edition
   Worskhops conducted in the past.
 
** Download the form
   Kindly download the [[form][form]], complete the checklist against each pre requisite,
   scan the form and mail it to us at [[engg@vlabs.ac.in]]
